### docker-compose.yml

version: '3.7'
services:
  naming-server:
    image: aravinthkaliyamoorthy/netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports: 
      - "8761:8761"
    restart: always
    depends_on:
      - currency-conversion-service
    networks:
      - currency-compose-network

  currency-conversion-service:
    image:  aravinthkaliyamoorthy/currency-conversion-service:0.0.2-SNAPSHOT
    ports: 
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
    depends_on:
      - currency-exchange-service
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: aravinthkaliyamoorthy/currency-exchange-service:0.0.2-SNAPSHOT
    restart: always
    depends_on:
      - mysql
    environment:
      RDS_HOSTNAME: mysql
    networks:
      - currency-compose-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: currency
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - currency-compose-network

# Volumes
volumes:
  mysql-database-data-volume:

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: