### docker-compose.yml

version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.5.3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - currency-compose-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    ports: 
      - "9411:9411"
    restart: always
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - currency-compose-network

  naming-server:
    image: aravinthkaliyamoorthy/netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports: 
      - "8761:8761"
      - "28787:8787"
    restart: always
    networks:
      - currency-compose-network
 
  zuul-api-gateway:
    image: aravinthkaliyamoorthy/netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT
    ports: 
      - "8765:8765"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - zipkin-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    image:  aravinthkaliyamoorthy/currency-conversion-service:0.0.2-SNAPSHOT
    ports: 
      - "8100:8100"
    restart: always
    environment:
      #CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - currency-exchange-service 
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: aravinthkaliyamoorthy/currency-exchange-service:0.0.2-SNAPSHOT
    restart: always
    ports: 
      - "8000:8000"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - naming-server
      - mysql
      - zipkin-server
    environment:
      RDS_HOSTNAME: mysql
    networks:
      - currency-compose-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: currency
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - currency-compose-network

# Volumes
volumes:
  mysql-database-data-volume:

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: